### ISSUE TITLE
Axegaz Customer UI help update

### ISSUE THREAD

**Issue by szdezso** [SkillTech-Organization/AXERP_UI#21]
**AC-01**
Update the text of the help at Axegaz Customer UI:

"Axegaz Transactions Manual
Transactions Grid"

to
"Axegaz (Card/Gas))Transactions Manual
(Card/Gas)Transactions Grid"

**Comment by C-63** [comment]
@szdezso 

![Image](https://github.com/user-attachments/assets/9bd66eff-3d5e-40f7-b1ad-8e98518aaa17)
